### ISSUE TITLE
Create a Flask endpoint which creates a new flavor

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#10]
Goal: the Flask endpoint should create a row in a new "flavors" table, using a name you provide as a parameter. This should create a new row in the flavors table, linked to all the packages you imported.

This should never create duplicate rows in the packages table.

To close this ticket, you will need to submit a PR and have it reviewed/merged by the rest of the team.

**Comment by JosiahRegencia** [comment]
I committed this one already. It's in the pull request

**Comment by greenmoss** [comment]
This task is to convert `create_flavor` to a pure API solution

**Comment by greenmoss** [comment]
Pending acceptance of #17
