### ISSUE TITLE
Docker setup on laptop

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#105]
Erikka, please set up Docker on your laptop. The goal is to run `docker-compose up` and have the Doveps cluster built and started. Please record the time from command to complete here.

**Comment by erikkaBaguio** [comment]
Hi Kurt,

Had problems with my OS configurations over the weekend. Decided to reinstall last night.
So I already set up Docker, and it took 10m 10s 37  to ran docker-compose up. 

![screenshot from 2018-02-26 17-10-38](https://user-images.githubusercontent.com/14104694/36662576-c203b5c0-1b19-11e8-9452-f6a049e95e58.png)
![screenshot from 2018-02-26 17-11-59](https://user-images.githubusercontent.com/14104694/36662577-c26198de-1b19-11e8-8497-188a87d3c326.png)

**Comment by greenmoss** [comment]
Great! I think we need to find a way to speed that up. Maybe that is a good follow-on task: experiment with getting the Docker rebuild faster. I think Docker natively supports building successive layers which *might* help.
