### ISSUE TITLE
Create a Flask endpoint which compares two flavors

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#11]
Goal: the Flask endpoint should show the package differences between two flavors. This will show any package names that are in one flavor but not the other.

You will need to import a second flavor so you can do the comparison. Use the API endpoint you created in #10 to import the second flavor. Use one of the other Vagrant files in the vagrants directory as your comparison flavor.

To close this ticket, you will need to submit a PR and have it reviewed/merged by the rest of the team.

**Comment by JosiahRegencia** [comment]
About this one, if I'm not mistaken, create_automation saves to the new "flavors" table and then compare both flavors right?

**Comment by greenmoss** [comment]
Pending changes/acceptance of #17
