### ISSUE TITLE
Fix the psycopg2 warning on Travis test output

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#118]
See https://travis-ci.org/Doveps/mono/builds/349113315#L929

`/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.`

**Comment by erikkaBaguio** [comment]
Made a PR:
https://github.com/Doveps/mono/pull/122

**Comment by greenmoss** [comment]
👍
