### ISSUE TITLE
Create a diagram

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#12]
Goal: provide a diagram of your understanding of... the database? (Please update the ticket if this is incorrect). Attach the diagram, or a link to it, to this ticket.

Quoting Slack:

> Hi, I'm confused with issue #10. Does that mean Flask is connected to 2 database systems?
> 
> kurt [9:00 AM] 
> No still postgres
> 
> [9:00] 
> Same database
> 
> jetregencia [10:10 AM] 
> Would it be possible to have a diagram?

**Comment by JosiahRegencia** [comment]
I realized that what I was looking for wasn't a diagram. I just forgot what it's actually called. Anyway, here is my own stuff based on how I understand issue #10 

I hope it's clear enough. I'm bad at this. haha

Link: https://drive.google.com/open?id=1rsC7KeX0i0ASBKghY1exnuX0i_Kreo0HbZitWxBlIM0

**Comment by greenmoss** [comment]
I updated the doc with comments based on our discussion today. Let me know if anything is unclear. The follow-on task for this will be to move it into the main `/docs` section of this repository. See #13 .
