### ISSUE TITLE
03-26-2018 report:

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#131]
Added a .env file supposedly for database environment configurations.
But according to this link: https://stackoverflow.com/questions/31644175/docker-compose-postgres-customize-database-details

Doesn't actually do the job. 

Also tried setting  the database name to postgres which is the default. I've been searching how to create database inside the sql file. And to create the tables inside that database

https://www.codeproject.com/Questions/438211/How-to-create-database-from-SQL-script
https://www.w3schools.com/sql/sql_create_db.asp

Does the job but I'm confused how it can add tables into it.

**Comment by greenmoss** [comment]
I think the key is going to be figuring out how to connect to the local db when it is up. Have you had any experience using the `psql` command line tool? It is actually not too bad. Let me see if I can come up with an example and post it on the wiki.

**Comment by greenmoss** [comment]
I updated the docs to include `psql` examples:

https://github.com/Doveps/mono/wiki/Developing-with-Docker

Let me know if that helps you make any headway. The `psql` should help prove that it's working. If you get to it from command line (credentials are in the test scripts if I recall correctly), that should let you also use it via pg_admin.
