### ISSUE TITLE
03-28-2018: Adding Loggers

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#133]
Had no experience about loggers prior to this one. So I actually had to study it first. Used these as reference:

* https://docs.python.org/2/howto/logging.html
* https://www.youtube.com/watch?v=-ARI4Cz-awo

Created a demo just to show the output:
* https://youtu.be/nKlwJ-ndjU4

**Comment by greenmoss** [comment]
Added comment on line for making logging output easier to read:

https://github.com/Doveps/mono/commit/618eb84204c7a91004c5491ec7dbedffa43c98fe#comments

So normal db + code + test will look like:

1. stop local postgres
2. start docker-compose db
3. run `python run.py`
4. make code changes
5. run tests
6. repeat steps 3-5 as needed
