### ISSUE TITLE
03-29-2018: Found problem.

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#134]
After some debugging. I found where the problem is. It's in the get_scanned.py. It doesn't seem to be called. For some reason. Posted a demo of it. Here's the link: https://youtu.be/171earrBaGE

PS. I did have background music along with it buuut thought you wouldn't approve of it so I removed all audio.

**Comment by greenmoss** [comment]
Really good debugging. The video shows you are hitting all the right areas: using db from container, connecting with savant in virtualenv, and running tests directly in virtualenv.

You were able to reproduce the behavior that is problematic, so the next step will be to add more debugging and find the rest of the problem.

Good work!
