### ISSUE TITLE
03-30-2018: Trying werkzeug inside the unit test

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#135]
So apparently, the files don't seem to be read.
![screenshot from 2018-03-30 18-28-09](https://user-images.githubusercontent.com/8079107/38135022-75376de8-3448-11e8-84ed-92ac3e0ca76e.png)

Most solutions online were the same. 
https://github.com/Doveps/mono/blob/efe5371c40533ff5afe6e3fdcd6d79d2a36297c7/savant/tests/test_basic.py#L46-L52

That seems to be the format.

Tried using werkzeug. Based it from this:
http://werkzeug.pocoo.org/docs/0.14/test/

https://github.com/Doveps/mono/blob/efe5371c40533ff5afe6e3fdcd6d79d2a36297c7/savant/tests/test_basic.py#L27-L38

The results are the same. I'm not sure if the request in results.py is the one that's wrong or is it the test.

**Comment by greenmoss** [comment]
Building from the previous ticket #133 , keep inserting debug statements until you find the discrepancy. For instance, in `/flavor/create`,  you could add a debug statement to check whether the uploaded file made it in:

https://github.com/Doveps/mono/blob/master/savant/app/results.py#L10

If it did, then you can follow the variables into the next step, and see if *those* variables made it in:

https://github.com/Doveps/mono/blob/master/savant/app/query.py#L24

Continue doing that for both the "working" manual insert, and compare it to the "non-working" tests.
