### ISSUE TITLE
04-02-2018: Reading from stdin

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#136]
Limited file uploads to only 1 file. 

https://github.com/Doveps/mono/blob/2c757d1b4c6b561d1514f8daec17aee40388fd60/savant/app/get_scanned.py#L26-L30

Added loggers based on the code above. The result is still the same. Through unit testing, it doesn't seem to read the contents of the file.
![screenshot from 2018-04-02 21-26-55](https://user-images.githubusercontent.com/8079107/38198252-9542b142-36be-11e8-9b98-f843f992ed69.png)

One more thing: In my curl commands, I use the flag -F. Reading from the site below, I learned the -F flag means that it reads from the stdin instead of the file itself. The unittest, somehow seems to be reading directly from the file. Hence, it doesn't read the contents, I guess (which is likely to be true).
http://manpages.ubuntu.com/manpages/xenial/man1/curl.1.html

Either I find a way to have the API read the file directly and not from stdin 

OR

Have the unit tests read from stdin instead of directly to the file. 

Which one should I do?

**Comment by JosiahRegencia** [comment]
Forgot to mention.  It's able to read the file. As opposed to multiple files, it's not able to detect any of them

**Comment by greenmoss** [comment]
Good debugging. I think you are getting closer.

Reading from STDIN is good for a single file. If you want to do multiple, I don't think you can do STDIN. If I remember correctly, we decided to do multiple per API call, so I guess we can't use -F.

**Comment by JosiahRegencia** [comment]
Seems like we could from STDIN for multiple files. It's what I did in the previous

**Comment by greenmoss** [comment]
I thought we had to specify multiple files using multiple arguments. STDIN is a single stream, so how would the parser know where one file ends and the next one begins?

**Comment by JosiahRegencia** [comment]
Flavor creation:

curl -F "files[]=@tests/Scanner_Files/33.33.33.50/find_debs_stdout.log" -F "files[]=@tests/Scanner_Files/33.33.33.50/find_groups_stdout.log" -F "files[]=@tests/Scanner_Files/33.33.33.50/find_shadow_stdout.log" -F "files[]=@tests/Scanner_Files/33.33.33.50/find_users_stdout.log" http://127.0.0.1:5000/doveps/api/flavor/create/



Comparison:
curl -F "files[]=@tests/Scanner_Files/33.33.33.51/find_debs_stdout.log" -F "files[]=@tests/Scanner_Files/33.33.33.51/find_groups_stdout.log" -F "files[]=@tests/Scanner_Files/33.33.33.51/find_shadow_stdout.log" -F "files[]=@tests/Scanner_Files/33.33.33.51/find_users_stdout.log" http://127.0.0.1:5000/doveps/api/flavor/compare/


Is that what this does?

**Comment by zerstoeren** [comment]
So you are trying to loop through the inputs?

**Comment by greenmoss** [comment]
I ran `curl --help` and it shows

`-F, --form CONTENT  Specify HTTP multipart POST data (H)`

so... maybe `-F` is correct after all

**Comment by JosiahRegencia** [comment]
Yup. In loops. Because in the original it saves all the uploaded files in a list
