### ISSUE TITLE
04-03-2018: Fixing file reading

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#137]
Figured this change in reading a file would work:

https://github.com/Doveps/mono/blob/0acaf09f5d68749f92f7bafa53e126764a62fe6e/savant/app/get_scanned.py#L51-L74

Worked well for a single upload as opposed to the previous ticket where even a single upload can't be read.

![screenshot from 2018-04-03 23-30-42](https://user-images.githubusercontent.com/8079107/38260351-f0961af8-3799-11e8-9c12-89cabc4007af.png)

I guess what I have to do next is to figure out how to upload an array of files in the test case

**Comment by greenmoss** [comment]
Looks like progress. Good work!
