### ISSUE TITLE
04-05-2018: Initializing Null Testcase

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#140]
I initialized the null test case. Got confused along the way as to how to implement it.
Created a new branch **null-testcase**

Here is the test case:

https://github.com/Doveps/mono/blob/7bbaa21f5b8365ed508e084db2f67b0e07b950e8/savant/tests/test_basic.py#L43-L50

I based it from this:

https://github.com/Doveps/mono/blob/7bbaa21f5b8365ed508e084db2f67b0e07b950e8/savant/app/query.py#L161-L176

What it does is it searches for any repetition in the DB. If it returns an empty list, then it passes.

![screenshot from 2018-04-05 23-49-31](https://user-images.githubusercontent.com/8079107/38376879-31e27f0e-392c-11e8-8d6a-72096e248768.png)

I could add more details in the testing. Just wanted to make sure first I'm on the right track.

**Comment by greenmoss** [comment]
Hi Josiah, I reviewed the PR. This is a good first pass at the logic. However for testing purposes we should focus on the `GET` and `CREATE` API endpoints. For instance:

* Use `CREATE` to insert multiple test entries into the DB. For example, use this API endpoint: https://github.com/Doveps/mono/blob/master/savant/app/results.py#L10
    * You will need a new test function with new test setup code, which will look very similar to existing `CREATE` test cases, for example this: https://github.com/Doveps/mono/blob/master/savant/tests/test_basic.py#L11
    * You will have to do some research on the conditions that would have have created duplicate rows in the db, and use that to inform your test entries
* Then use `GET` to retrieve the same entries from the DB. For example, use this API endpoint: https://github.com/Doveps/mono/blob/master/savant/app/results.py#L77
    * In your new test function after the test setup code, you will then need to call the API `GET`
    * In the new test function, count your results. What we want is no duplicate records, so the count should reflect that. For instance, if we did `CREATE` once with 5 records, and `CREATE` again with the same 5, the count at the end should be 5. If it is instead 10, our test would now catch that error.


Let me know if you have questions, we can do a video chat if you want.
