### ISSUE TITLE
04-06-2018: Test case for record knowledge

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#141]
https://github.com/Doveps/mono/blob/554a7fe2b8f77779a1a772261fcadcfc402c3e11/savant/tests/test_basic.py#L47-L59

Added test case for record knowledge. I just asserted the messages if they're equal. 

Waiting whether my null test cases are on the right track also

**Comment by greenmoss** [comment]
Hi, thanks for the report. This code looks really good! I see you are using the API endpoints to verify operations, that is exactly what we want to be doing. You are definitely on the right track here.

It looks like the code you posted is on branch `deeper_nulltestcase`, as part of PR #123 ; is that correct?

**Comment by JosiahRegencia** [comment]
This isn't posted on branch `deeper_nulltestcase`. I created a new branch `null-testcase` @greenmoss
