### ISSUE TITLE
04-09-2018 Running null test case after create and then after compare functions

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#142]
Trying to run the null test case after a create endpoint and then after the compare endpoint. 

https://github.com/Doveps/mono/blob/4039d34fc2ec035a03221e54fb113b3864e8760e/savant/tests/test_basic.py#L25-L38

![screenshot from 2018-04-10 00-03-29](https://user-images.githubusercontent.com/8079107/38508941-0bacb4b0-3c53-11e8-91ec-10af6d463e61.png)
 Currently stuck at that.

I think I can get that to work tomorrow. Once I'm done with that I'll explain what I did.

**Comment by greenmoss** [comment]
Good approach. I note there are "1/2/3... " numbers in the test names. Can you explain your reasoning?

I would suggest avoiding those numbers, otherwise you have to remember to keep them in order, without holes in the sequence, etc. It could be a lot of micromanagement.
