### ISSUE TITLE
04-11-2018 : Code formatting

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#144]
Didn't do much today. Waiting on feedback from ticket #143 

I did reformatting in the code for today. Removed comments and some unnecessary lines in the python files.

Refer to this commit: [Click here](https://github.com/Doveps/mono/commit/3954b01865c878c1d1a95375854f591603a74dcc)

**Comment by greenmoss** [comment]
OK, thanks for keeping at it and not getting blocked! I hope my answers helped.
