### ISSUE TITLE
04-12-2018: Report on updated testing

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#145]
Made the changes based on the meeting earlier.
 Added the count functions to the API:

https://github.com/Doveps/mono/blob/c3ee51a704059a77c9c7517b9e09a47518818bb8/savant/app/results.py#L97-L124

Added psycopg2 config in unit tests
https://github.com/Doveps/mono/blob/c3ee51a704059a77c9c7517b9e09a47518818bb8/savant/tests/test_basic.py#L10-L20

But it doesn't seem to go well with travis. I guess it has a lot to do with mono_savant_1 starting already when mono_db_1 hasn't finished yet.

[Changes made here](https://github.com/Doveps/mono/commit/c3ee51a704059a77c9c7517b9e09a47518818bb8)

I'm still researching on the unit test structures you mentioned earlier. [Found this](http://www.patricksoftwareblog.com/python-unit-testing-structuring-your-project/). Seems similar to what I did, though. I'm going to dig deeper tomorrow.

**Comment by greenmoss** [comment]
Looks good!
