### ISSUE TITLE
04-13-2018 : Fixed Query issues and Issues making travis fail

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#146]
I was reading about psycopg2 patterns because not closing the cursor and the connection in `query.py` really bothered my. I read that it builds up cache. I read from this [article](http://initd.org/psycopg/articles/2010/10/22/passing-connections-functions-using-decorator/) about using decorators but from some forums I also read that decorators inside a class is pointless. This [forum](https://softwareengineering.stackexchange.com/questions/200522/how-to-deal-with-database-connections-in-a-python-library-module) led me to the solution, instead. 
https://github.com/Doveps/mono/blob/02df17a70bfbea7be9b4ea1b994333e6616a9a27/savant/app/query.py#L209-L212

Short and effective. Surely works.

At the same time, had to put these functions back in `query.py`:

https://github.com/Doveps/mono/blob/02df17a70bfbea7be9b4ea1b994333e6616a9a27/savant/app/query.py#L180-L207

I transferred it to `results.py` in issue #145 but it doesn't go well with` travis` testing. it fails. Putting it back in `query.py` fixes that issue.

Screenshot of passed build:

![screenshot from 2018-04-13 23-10-26](https://user-images.githubusercontent.com/8079107/38742720-e483b882-3f6f-11e8-9b9d-c8f048ee7b03.png)

**Comment by greenmoss** [comment]
Good, I remember using `__del__` before too, seems like the right way to do it.

I notice those four functions are mostly identical. Any ideas on de-duplicating?
