### ISSUE TITLE
Upload an intro video with new headphone/microphone

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#18]
Goal: research a headset with microphone. We are looking for good audio quality on the demos.

You can close this once you've uploaded a video to Youtube using your new headset.

For the demo, please show the Travis integration from #19

**Comment by JosiahRegencia** [comment]
Using the new headset! 
It works!
https://youtu.be/vWmpKBMKSs4

**Comment by greenmoss** [comment]
Please upload a video showing Travis execution

**Comment by JosiahRegencia** [comment]
@greenmoss I uploaded it in the other ticket

**Comment by JosiahRegencia** [comment]
Anyway, here it is

https://www.youtube.com/watch?v=rFMkLnIZjsM&t=273s

**Comment by greenmoss** [comment]
Looks good!
