### ISSUE TITLE
Get the tests to pass

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#25]
Goal: get tests that you added in #19 to pass Travis, and display the Travis "passing" status button on the README.

**Comment by JosiahRegencia** [comment]
UPDATE:

I actually have to fix this:     os.chdir("/home/josiah/Documents/Doveps/mono/scanner/local/33.33.33.50/")

And also for some reason it doesn't read psycopg2 that well.
    connection = psycopg2.connect("dbname='Doveps' user='postgres' host='localhost' password='postgres'")
that part does not work on travis YET. May have to find a configuration.

**Comment by greenmoss** [comment]
Hmm, does this need to be broken out? That is: testing db.

**Comment by JosiahRegencia** [comment]
Probably the os.chdir, part. I think

**Comment by JosiahRegencia** [comment]
Update:

Fixed the os.chdir part already. currently figuring out how to be able to make steps 1 and 2 from this link: http://sharadchhetri.com/2014/05/04/how-to-install-virtualbox-in-ubuntu-14-04-lts-trusty-tahr/

in Travis

**Comment by greenmoss** [comment]
"Cheating" for test by uploading the file artifact as part of the test

**Comment by greenmoss** [comment]
https://docs.travis-ci.com/user/database-setup/#PostgreSQL

**Comment by JosiahRegencia** [comment]
I actually pushed 33.33.33.50 and 33.33.33.51. Easiest fix and cheat. Hehe. I'm still figuring out the database stuff. somehow it doesn't recognize some files inside the directory. Although I have moved forward.

**Comment by zerstoeren** [comment]
That is good news.  Thanks Josiah.

**Comment by JosiahRegencia** [comment]
I wasn't really sure whether you guys were gonna be pleased or not. It was inside .gitignore,however.
