### ISSUE TITLE
Test a VM build on Travis

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#26]
See if you can get Travis to start up a VM and execute it.

**Comment by greenmoss** [comment]
Related to Travis tests in #25

**Comment by greenmoss** [comment]
@JosiahRegencia please document the work you have done so far, and then we will close this

**Comment by JosiahRegencia** [comment]
What I did so I could get vagrant to work was in the before_script I wrote these following Linux terminal commands for installing vagrant and virtualbox:

- sudo echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" >> vim /etc/apt/sources.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install virtualbox-5.1
  - sudo apt-get install dkms
  - sudo apt-get install virtualbox-dkms
  - sudo apt-get install vagrant
  - sudo apt-get update
  - ssh-keygen -t rsa -f /home/travis/.ssh/id_rsa -q -P ""
  - touch ~/.ssh/known_hosts

**Comment by JosiahRegencia** [comment]
https://www.youtube.com/watch?v=rFMkLnIZjsM&feature=youtu.be

**Comment by greenmoss** [comment]
OK, thanks. I don't think a VM will work with Travis, because it's probably already running on a VM 😄
