### ISSUE TITLE
POST scanner files for flavor creation

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#32]
Goal: when creating a flavor, all files should be supplied via POST

This should replace savant/app/results.py#L14, which reads files directly from the file system.

**Comment by JosiahRegencia** [comment]
Does this mean that this should not read all the files directly in one command?

**Comment by greenmoss** [comment]
If it's possible to do it in one command, then do that. I haven't tried it before though. Check here for ideas:

http://pythonhosted.org/Flask-Uploads/

**Comment by JosiahRegencia** [comment]
Just an update: I could manage uploading one file. I'm still figuring out how to upload multiple files in one command.
for travis, I still don't know how to run a curl command in travis

**Comment by JosiahRegencia** [comment]
trouble with uploading is with, curl. As of the moment

**Comment by zerstoeren** [comment]
how are you doing it now?

you might try something like this:

after_deploy:
  - "curl -H 'Authorization: token someToken'
\"https://api.github.com/repos/:owner/:repo/releases/tags/$TRAVIS_TAG\""

**Comment by JosiahRegencia** [comment]
I put it under the script. Although if I'm using my Ubuntu terminal, I could only upload 1 file at a time. Uploading multiple files at a time gives me this: curl: (6) Could not resolve host:  -F

**Comment by zerstoeren** [comment]
ah... try putting it in a bash script that you can loop until all of the
files are pushed.

**Comment by JosiahRegencia** [comment]
What do you mean?

**Comment by greenmoss** [comment]
Regarding uploading multiple files:
One file is fine to start with; we will add a follow-on task for uploading multiple files
