### ISSUE TITLE
Speed up flavor creation

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#39]
Objective: reduce flavor import to under one second

From the demo, it appears that flavor imports take quite a while. These are pretty small files, so we will need better performance. Look at python profiling tools to get you started.

Let me know if you have worked with profilers before. If not, figuring out how to profile can be a separate ticket.

**Comment by JosiahRegencia** [comment]
Just realized that what makes the flavor creation slow is the insertion of the data to the database. Not yet sure what to do but I'll find a way.

**Comment by zerstoeren** [comment]
I would be curious what could be causing this slowness.  Hopefully it isn't
disk i/o, but i'm curious if a MQ system might be beneficial if the problem
is hardware over DB or code optimization.

**Comment by JosiahRegencia** [comment]
Currently finding a way to commit all data just once. It commits for every insertion making it super slow
