### ISSUE TITLE
Upload a test screen capture video

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#4]
Goal: Upload a test video to the Doveps Youtube channel

You will be recording many demo videos. This will be your first video, and work out the kinks with uploading to Doveps Youtube. The demo can be as simple as you like. It should include video of your screen, and some test audio.

To close this ticket, you should include a link to the uploaded video.

**Comment by JosiahRegencia** [comment]
https://youtu.be/l7N_T6DgzbA
