### ISSUE TITLE
Verify OpenVPN + Openstack connection

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#43]
For @JosiahRegencia to verify test environment

Create an Openstack VM, and log into it, using @zerstoeren connection. Connection info will be provided separately, because this is a public-viewable ticket :smile:

**Comment by zerstoeren** [comment]
sending you the details in an email now.

**Comment by zerstoeren** [comment]
found a VPN bug in my firewall that Cisco says is scheduled to be released this week and can open apply the upgrades then that will hopefully resolve the issue.

if their fix does not work, i will stand up some infrastructure that i have on the web for him.

**Comment by zerstoeren** [comment]
Bug in my firewall is fixed.  I have been able to VPN and access the devices that Josiah needs from my phone to verify connectivity.  The instructions should be the same as before.

**Comment by JosiahRegencia** [comment]
![screenshot from 2017-11-16 22 15 28](https://user-images.githubusercontent.com/8079107/32896007-d1b5e68e-cb1c-11e7-8a15-da6efee46d39.png)
![screenshot from 2017-11-16 22 15 32](https://user-images.githubusercontent.com/8079107/32896010-d23e265c-cb1c-11e7-99fe-aee0e1bee31c.png)

I'm not really sure though, but is this correct?

**Comment by zerstoeren** [comment]
You are in the correct project.   If you click on Project -> Instances,
that will take you to the page to create a new VM.

**Comment by JosiahRegencia** [comment]
![screenshot from 2017-11-17 03 20 39](https://user-images.githubusercontent.com/8079107/32911161-5026e5b2-cb46-11e7-91f7-0e8e08563cb7.png)

Is that the way?

**Comment by JosiahRegencia** [comment]
![screenshot from 2017-11-17 03 25 05](https://user-images.githubusercontent.com/8079107/32911361-ee2bbbde-cb46-11e7-923d-f2f89bda016d.png)

**Comment by zerstoeren** [comment]
That's it.  Looks like you got a VM stood up.  :)

**Comment by JosiahRegencia** [comment]
Somehow that tab freezes, though.

**Comment by greenmoss** [comment]
@JosiahRegencia did you check again? Sometimes that network screen stays up for a few minutes. See if you can log in now.

**Comment by greenmoss** [comment]
@JosiahRegencia did you get the login to work? I'd like to close this ticket.

**Comment by zerstoeren** [comment]
The login to openstack?

**Comment by greenmoss** [comment]
sorry, I meant "log in to the VM"

**Comment by zerstoeren** [comment]
I can't verify that.

**Comment by JosiahRegencia** [comment]
Hi. I'm so sorry. Our internet got cut off. We forgot to pay. Hehe. I'm going to be paying it later, though
