### ISSUE TITLE
Demo faster flavor creation

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#48]
Post a demo for the new, faster flavor code from #39

**Comment by greenmoss** [comment]
Seems like this was uploaded:

https://www.youtube.com/watch?v=qWTatvoEov0

@JosiahRegencia please confirm, then I will close this

**Comment by JosiahRegencia** [comment]
https://www.youtube.com/watch?v=qWTatvoEov0&t=48s
Here it is @greenmoss
