### ISSUE TITLE
create an API endpoint "action/create"

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#49]
This endpoint will accept parameters:
* the JSON file that you generated from `flavor/compare`
* "name", which is text
* "resource", which defaults to and currently only accepts `Package`
* "action", which defaults to and currently only accepts `New`

**Comment by JosiahRegencia** [comment]
does this mean that once I run flavor/compare I must generate a json file? 
I'm not sure what you mean by Package and New. 
Also, may I ask what the "name" is for?

**Comment by JosiahRegencia** [comment]
From what I understand, "name" is either name in debs, group_name in groups, username in both shadow and users. is that correct?

**Comment by greenmoss** [comment]
Regarding json: correct
Regarding Package/New: in the example from the demo, your json is the result of "Package", "New", "apache2", so you need to record that
Regarding names: correct

**Comment by JosiahRegencia** [comment]
ooh okay. I get it now. Thanks a lot.
