### ISSUE TITLE
Create a new table "knowledge"

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#50]
Goal: the new `knowledge` table stores connections between rows in the `Debs`, `Users`, etc tables and actions.

For instance, you ran a comparison between 33.33.33.50 and 33.33.33.51, and found new Debs and Users. Then you ran `action/create` from #49. The parameters from `action/create` should store the name, resource, and action in the `knowledge` table, along with links to the `Debs`, `Users`, etc tables.

**Comment by JosiahRegencia** [comment]
Does this mean the link to the row in the table or to the table itself?

**Comment by greenmoss** [comment]
link to the row in the table

**Comment by JosiahRegencia** [comment]
I just realized something. What it's supposed to save is the results to comparison right? If so, the results to the comparison are not present in either debs, groups, user, shadow since they are the base tables.

**Comment by greenmoss** [comment]
You created json output from #49. That has a bunch of packages, etc in it. You need to make a new knowledge entry for all of that information: the debs, groups, etc. That knowledge entry says "when I installed deb apache2, it added all these debs, groups, etc". The "knowledge" database table holds that information.

**Comment by greenmoss** [comment]
I'm going to call this one done, because you did create the table. However this needs some follow-up work.
