### ISSUE TITLE
Look for Github-friendly continuous integration testing systems

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#7]
We need to start auto-testing PRs for Doveps. What should we use?

Should be free for Open Source projects.

I found this list:

https://github.com/marketplace/category/continuous-integration

**Comment by zerstoeren** [comment]
Currently reading up on

https://travis-ci.org

**Comment by zerstoeren** [comment]
I have done some setup and testing with Travis-CI and seems to be a fairly easy setup process.  Most of the setup can be done from the Travis-CI GUI and then dropping a .travis.yml file with the language, version, and library requirements along with the test criteria.

A python .travis.yml file example for python is below, but Travis-CI supports a crap ton of language.  Over 20 I think.  

Have the .travis.yml file in the push will trigger Travis-CI to do its thing.
```bash
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
```

**Comment by greenmoss** [comment]
Thanks @zerstoeren I think this is done. OK to close?

**Comment by zerstoeren** [comment]
Let's close it.
