### ISSUE TITLE
Friday January 5, 2018 Daily Report

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#79]
01-05-18 - 1:21

Branch used: travis-docker

1. Used Docker to run python commands:

    Used docker build mono-test and docker run mono-test instead of python command

    Reference: https://runnable.com/docker/python/dockerize-your-python-application
2. I tried adding a unittest as a service in docker-compose. Ended up with this error: services.unittest.depends_on contains an invalid type, it should be an array

    Reference: http://developerautomation.com/unit-testing-with-a-docker-container/#comments

I'll keep adding reports on what I'll be doing in the comment section

**Comment by JosiahRegencia** [comment]
3. Based docker-compose config on https://discuss.circleci.com/t/multi-container-application-stack-testing-with-docker-or-docker-compose-on-circleci/580/3

4. I was able to run the test cases in docker-compose in this build: https://travis-ci.org/Doveps/mono/builds/325393568
      I think I have to have it run last, though.

**Comment by greenmoss** [comment]
I'm not sure if the output in point 4 is from current code, but that is due to the `/code` directory not mounting. Check your Docker volumes.
